language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
install: "pip install -r requirements.txt"
script: nosetests
branches:
  only:
    - master
notifications:
  slack: keepontrucking:ih7fQF17SF3RKTUPlvEdo5Zb
